play-profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgresdbt
      user: dbtuser
      password: (changeme)
      port: 5432
      dbname: dbtdb
      schema: dbt
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default
      #search_path: [optional, override the default postgres search_path]
      #role: [optional, set the role dbt assumes when executing queries]
      #sslmode: [optional, set the sslmode used to connect to the database]
