---
name: play_dbt
version: '1.0.0'
config-version: 2

profile: play-profile

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

on-run-start:
  - "create table if not exists audit (model text, state text, time timestamp)"

models:
  play_dbt:
    example:
      materialized: table
      my_first_variable: true
      my_second_variable: 2020
      my_third_variable: 1
      pre-hook: >
        insert into audit (model, state, time)
        values ('{{this.name}}', 'starting model deployment', current_timestamp)
